import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{BrowserRouter,NavLink,Route,Routes,useNavigate}from'react-router-dom';import{Activity,AlertTriangle,Bell,BookOpen,CheckCircle2,ChevronRight,Clock,FileKey2,FileText,Gauge,KeyRound,LayoutDashboard,LockKeyhole,RefreshCw,Search,Settings,Shield,ShieldCheck,Users,XCircle}from'lucide-react';import{ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,PieChart,Pie,Cell}from'recharts';import{usePKI}from'./store';import{lifecycle}from'./data';import'./style.css';

const nav=[
['Overview',[['/','Dashboard',LayoutDashboard]]],
['Certificate Management',[['/request','New Request',FileKey2],['/my-requests','My Requests',FileText],['/certificates','Certificates',ShieldCheck],['/renewals','Renewals',RefreshCw],['/revocation','Revocation',XCircle]]],
['Secure Signing',[['/signing','Signing Requests',KeyRound],['/my-signing','My Signing Requests',FileText],['/hsm','HSM / Key Vault',LockKeyhole]]],
['Policy Management',[['/policies','Crypto Policies',Shield],['/compliance','Compliance Rules',CheckCircle2],['/trust','Trust Configuration',BookOpen]]],
['Audit & Monitoring',[['/audit','Audit Logs',FileText],['/alerts','Events & Alerts',AlertTriangle],['/health','System Health',Activity]]],
['User Management',[['/users','Users',Users],['/roles','Roles & Permissions',ShieldCheck]]],
['Platform',[['/settings','Settings',Settings]]]
];

function Shell(){const [q,setQ]=useState('');const navg=useNavigate();const toasts=usePKI(s=>s.toasts);return <div className="app"><aside><div className="brand"><div className="brandmark">PKI</div><div><b>Control Plane</b><small>Certificate Lifecycle</small></div></div>{nav.map(([group,items])=><div className="navgroup" key={group}><label>{group}</label>{items.map(([to,name,I])=><NavLink key={to} to={to} end={to==='/'}><I size={17}/><span>{name}</span></NavLink>)}</div>)}</aside><main><header><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&q.trim())navg('/certificates?search='+encodeURIComponent(q))}} placeholder="Search certificates, requests, users..."/></div><div className="headerRight"><span className="env">PRODUCTION</span><Bell size={18}/><div className="avatar">VB</div><div><b>Varsha</b><small>Security Admin</small></div></div></header><section className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/request" element={<NewRequest/>}/><Route path="/my-requests" element={<Requests mine/>}/><Route path="/certificates" element={<Certificates/>}/><Route path="/renewals" element={<CertificateAction mode="renew"/>}/><Route path="/revocation" element={<CertificateAction mode="revoke"/>}/><Route path="/signing" element={<Signing/>}/><Route path="/my-signing" element={<Signing mine/>}/><Route path="/hsm" element={<HSM/>}/><Route path="/policies" element={<Managed kind="policies" title="Crypto Policies"/>}/><Route path="/compliance" element={<Managed kind="complianceRules" title="Compliance Rules"/>}/><Route path="/trust" element={<Managed kind="trust" title="Trust Configuration"/>}/><Route path="/audit" element={<Audit/>}/><Route path="/alerts" element={<Alerts/>}/><Route path="/health" element={<Health/>}/><Route path="/users" element={<Managed kind="users" title="Users"/>}/><Route path="/roles" element={<Roles/>}/><Route path="/settings" element={<SettingsPage/>}/></Routes></section>{toasts.length>0&&<div className="toasts">{toasts.map(t=><div className={'toast '+t.type} key={t.id}>{t.message}</div>)}</div>}</main></div>}

const Page=({title,sub,action,children})=><><div className="pagehead"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>{children}</>;
const Badge=({children})=><span className={'badge '+String(children).toLowerCase().replaceAll(' ','-')}>{children}</span>;
const fmt=d=>new Date(d).toLocaleDateString('en-IE',{day:'2-digit',month:'short',year:'numeric'});
const Table=({cols,rows})=><div className="card tablewrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows}</tbody></table></div>;

function Dashboard(){const s=usePKI();const active=s.certificates.filter(x=>x.status==='Active').length,exp=s.certificates.filter(x=>x.status==='Expiring').length,pending=s.requests.filter(x=>x.status==='Pending').length,rev=s.certificates.filter(x=>x.status==='Revoked').length;const top=s.certificates.filter(x=>x.status==='Expiring').sort((a,b)=>new Date(a.expiryDate)-new Date(b.expiryDate)).slice(0,5);return <Page title="PKI Control Plane" sub="Enterprise certificate lifecycle, trust and security operations"><div className="kpis">{[['Active Certificates',active,ShieldCheck],['Expiring Soon',exp,Clock],['Pending Approvals',pending,FileText],['Revoked',rev,XCircle]].map(([a,b,I])=><div className="card kpi" key={a}><I/><div><small>{a}</small><strong>{b}</strong></div></div>)}</div><div className="grid2"><div className="card"><div className="cardtitle">Certificate Lifecycle <small>Last 6 months</small></div><ResponsiveContainer width="100%" height={245}><BarChart data={lifecycle}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="m"/><YAxis/><Tooltip/><Bar dataKey="issued" fill="#3b82f6"/><Bar dataKey="renewed" fill="#10b981"/><Bar dataKey="expiring" fill="#f59e0b"/></BarChart></ResponsiveContainer></div><div className="card"><div className="cardtitle">Security Posture</div><div className="posture"><PieChart width={180} height={180}><Pie data={[{v:92},{v:8}]} dataKey="v" innerRadius={62} outerRadius={78} startAngle={90} endAngle={-270}><Cell fill="#10b981"/><Cell fill="#123047"/></Pie></PieChart><div><strong>92</strong><span>/100</span></div></div><div className="minirow"><span>Policy compliance</span><b>96%</b></div><div className="minirow"><span>HSM availability</span><b>99.97%</b></div></div></div><div className="grid2"><div><h2>Top Expiring Certificates</h2><Table cols={['Common Name','Environment','Expires','Status']} rows={top.map(x=><tr key={x.id}><td><b>{x.commonName}</b><small>{x.type}</small></td><td>{x.environment}</td><td>{fmt(x.expiryDate)}</td><td><Badge>{x.status}</Badge></td></tr>)}/></div><div><h2>Recent Activity</h2><div className="card feed">{s.auditLogs.slice(0,7).map(x=><div key={x.id}><span className="dot"/><div><b>{x.event.replaceAll('_',' ')}</b><p>{x.details}</p><small>{new Date(x.timestamp).toLocaleString()}</small></div></div>)}</div></div></div></Page>}

function NewRequest(){const create=usePKI(s=>s.createRequest),toast=usePKI(s=>s.toast);const navg=useNavigate();const [step,setStep]=useState(1);const [f,setF]=useState({commonName:'',type:'TLS Server',environment:'Production',keyAlgorithm:'RSA-3072',validity:365,sans:'',justification:''});const valid=f.commonName.includes('.')&&Number(f.validity)<=398;return <Page title="New Certificate Request" sub="Request a certificate through policy validation and approval"><div className="steps">{['Certificate Details','Policy Validation','Review & Submit'].map((x,i)=><div className={step>=i+1?'on':''} key={x}><span>{i+1}</span>{x}</div>)}</div><div className="card formcard">{step===1&&<><Field l="Common Name" v={f.commonName} set={v=>setF({...f,commonName:v})} p="api.service.internal"/><div className="formgrid"><Select l="Certificate Type" v={f.type} set={v=>setF({...f,type:v})} a={['TLS Server','Client Auth','Code Signing']}/><Select l="Environment" v={f.environment} set={v=>setF({...f,environment:v})} a={['Production','Staging','Development','QA','DR']}/><Select l="Key Algorithm" v={f.keyAlgorithm} set={v=>setF({...f,keyAlgorithm:v})} a={['RSA-3072','RSA-2048','ECDSA P-256','ECDSA P-384']}/><Select l="Validity Period" v={f.validity} set={v=>setF({...f,validity:Number(v)})} a={[90,180,365,398]}/></div><Field l="Subject Alternative Names" v={f.sans} set={v=>setF({...f,sans:v})} p="api.service.internal, api-alt.service.internal"/><Field l="Business Justification" v={f.justification} set={v=>setF({...f,justification:v})} p="Purpose and owning service"/></>}{step===2&&<div className="validation"><CheckCircle2/><h2>Policy validation</h2>{[['Common name format',f.commonName.includes('.')],['Approved key algorithm',!f.keyAlgorithm.includes('1024')],['Validity within policy',Number(f.validity)<=398],['Environment policy mapped',true]].map(([x,ok])=><div className="check" key={x}>{ok?<CheckCircle2/>:<XCircle/>}<span>{x}</span><Badge>{ok?'Passed':'Failed'}</Badge></div>)}</div>}{step===3&&<div className="review">{Object.entries(f).map(([k,v])=><div key={k}><small>{k.replace(/([A-Z])/g,' $1')}</small><b>{String(v)||'—'}</b></div>)}</div>}<div className="actions">{step>1&&<button className="secondary" onClick={()=>setStep(step-1)}>Back</button>}{step<3?<button onClick={()=>setStep(step+1)} disabled={step===1&&!valid}>Next <ChevronRight size={16}/></button>:<button onClick={()=>{create(f);toast('Certificate request submitted for approval');navg('/my-requests')}}>Submit Request</button>}</div></div></Page>}

const Field=({l,v,set,p})=><label className="field"><span>{l}</span><input value={v} placeholder={p} onChange={e=>set(e.target.value)}/></label>;
const Select=({l,v,set,a})=><label className="field"><span>{l}</span><select value={v} onChange={e=>set(e.target.value)}>{a.map(x=><option key={x}>{x}</option>)}</select></label>;

function Requests({mine=false}){const req=usePKI(s=>s.requests),decide=usePKI(s=>s.decideRequest),toast=usePKI(s=>s.toast);const rows=(mine?req.filter(x=>x.requester==='Varsha'):req).slice(0,80);return <Page title={mine?'My Requests':'Pending Approvals'} sub={mine?'Track certificate requests you submitted':'Review policy-compliant certificate requests'}><Table cols={['Request ID','Common Name','Type','Environment','Requester','Created','Status','Actions']} rows={rows.map(x=><tr key={x.id}><td>{x.id}</td><td><b>{x.commonName}</b></td><td>{x.type}</td><td>{x.environment}</td><td>{x.requester}</td><td>{fmt(x.createdAt)}</td><td><Badge>{x.status}</Badge></td><td>{!mine&&x.status==='Pending'?<div className="rowactions"><button onClick={()=>{decide(x.id,'approve');toast('Request approved')}}>Approve</button><button className="danger" onClick={()=>{decide(x.id,'reject');toast('Request rejected','warn')}}>Reject</button></div>:<button className="secondary">View</button>}</td></tr>)}/></Page>}

function Certificates(){const certs=usePKI(s=>s.certificates);const [q,setQ]=useState(''),[env,setEnv]=useState('All'),[status,setStatus]=useState('All');const rows=useMemo(()=>certs.filter(x=>(x.commonName+x.serial+x.owner).toLowerCase().includes(q.toLowerCase())&&(env==='All'||x.environment===env)&&(status==='All'||x.status===status)).slice(0,100),[certs,q,env,status]);return <Page title="Certificate Inventory" sub="Search and monitor certificates across managed environments"><Filters q={q} setQ={setQ} env={env} setEnv={setEnv} status={status} setStatus={setStatus}/><Table cols={['Certificate','Type','Environment','Issuer','Expiry','Algorithm','Status']} rows={rows.map(x=><tr key={x.id}><td><b>{x.commonName}</b><small>{x.serial}</small></td><td>{x.type}</td><td>{x.environment}</td><td>{x.issuer}</td><td>{fmt(x.expiryDate)}</td><td>{x.keyAlgorithm}</td><td><Badge>{x.status}</Badge></td></tr>)}/></Page>}
function Filters({q,setQ,env,setEnv,status,setStatus}){return <div className="filters"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search inventory"/></div><select value={env} onChange={e=>setEnv(e.target.value)}>{['All','Production','Staging','Development','QA','DR'].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}>{['All','Active','Expiring','Expired','Revoked'].map(x=><option key={x}>{x}</option>)}</select></div>}

function CertificateAction({mode}){const certs=usePKI(s=>s.certificates),act=usePKI(s=>s.updateCertificate),toast=usePKI(s=>s.toast);const rows=certs.filter(x=>mode==='renew'?['Expiring','Expired'].includes(x.status):x.status!=='Revoked').slice(0,70);return <Page title={mode==='renew'?'Certificate Renewals':'Certificate Revocation'} sub={mode==='renew'?'Renew certificates approaching expiry':'Revoke certificates and preserve lifecycle evidence'}><Table cols={['Common Name','Environment','Expiry','Status','Action']} rows={rows.map(x=><tr key={x.id}><td><b>{x.commonName}</b></td><td>{x.environment}</td><td>{fmt(x.expiryDate)}</td><td><Badge>{x.status}</Badge></td><td><button className={mode==='revoke'?'danger':''} onClick={()=>{act(x.id,mode);toast(`Certificate ${mode==='renew'?'renewed':'revoked'}`,mode==='revoke'?'warn':'success')}}>{mode==='renew'?'Renew':'Revoke'}</button></td></tr>)}/></Page>}

function Signing({mine=false}){const xs=usePKI(s=>s.signingRequests),create=usePKI(s=>s.createSigning),decide=usePKI(s=>s.decideSigning),toast=usePKI(s=>s.toast);const [open,setOpen]=useState(false),[f,setF]=useState({artifact:'',algorithm:'SHA256-RSA',environment:'Production',keyProfile:'Production Signing Key',justification:'',changeRef:''});const rows=(mine?xs.filter(x=>x.requester==='Varsha'):xs).slice(0,60);return <Page title={mine?'My Signing Requests':'Signing Requests'} sub={mine?'Track secure signing requests and evidence':'Review and control secure signing operations'} action={mine&&<button onClick={()=>setOpen(true)}>New Secure Signing Request</button>}><Table cols={['Request ID','Artifact','Requester','Algorithm','Environment','Created','Status','Actions']} rows={rows.map(x=><tr key={x.id}><td>{x.id}</td><td><b>{x.artifact}</b></td><td>{x.requester}</td><td>{x.algorithm}</td><td>{x.environment}</td><td>{fmt(x.createdAt)}</td><td><Badge>{x.status}</Badge></td><td>{!mine&&x.status==='Pending'?<div className="rowactions"><button onClick={()=>decide(x.id,'Approved')}>Approve</button><button className="danger" onClick={()=>decide(x.id,'Rejected')}>Reject</button></div>:<button className="secondary">Evidence</button>}</td></tr>)}/>{open&&<div className="modalback"><div className="modal"><div className="modalhead"><h2>New Secure Signing Request</h2><button className="icon" onClick={()=>setOpen(false)}>×</button></div><Field l="Artifact / Package" v={f.artifact} set={v=>setF({...f,artifact:v})} p="release-2.4.1.zip"/><div className="formgrid"><Select l="Algorithm" v={f.algorithm} set={v=>setF({...f,algorithm:v})} a={['SHA256-RSA','ECDSA-SHA256']}/><Select l="Environment" v={f.environment} set={v=>setF({...f,environment:v})} a={['Production','Staging','Development']}/></div><Field l="Signing Key / Profile" v={f.keyProfile} set={v=>setF({...f,keyProfile:v})}/><Field l="Change / Ticket Reference" v={f.changeRef} set={v=>setF({...f,changeRef:v})} p="CHG-2026-00421"/><Field l="Business Justification" v={f.justification} set={v=>setF({...f,justification:v})}/><div className="actions"><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button disabled={!f.artifact} onClick={()=>{create(f);toast('Signing request submitted');setOpen(false)}}>Submit Request</button></div></div></div>}</Page>}

function HSM(){const hsms=usePKI(s=>s.hsms);const [selected,setSelected]=useState(null);return <Page title="HSM / Key Vault" sub="Cryptographic boundary health and key-service visibility"><div className="cards3">{hsms.map(x=><div className="card service" key={x.id} onClick={()=>setSelected(x)}><div className="servicehead"><LockKeyhole/><Badge>{x.status}</Badge></div><h2>{x.name}</h2><p>{x.region}</p><div className="minirow"><span>Healthy nodes</span><b>{x.healthyNodes}/{x.nodes}</b></div><div className="minirow"><span>Latency</span><b>{x.latency} ms</b></div><div className="minirow"><span>Uptime</span><b>{x.uptime}%</b></div></div>)}</div>{selected&&<div className="card detail"><h2>{selected.name} — Operational Detail</h2>{selected.logs.map(x=><p key={x}>✓ {x}</p>)}<button className="secondary" onClick={()=>setSelected(null)}>Close</button></div>}</Page>}

function Managed({kind,title}){const xs=usePKI(s=>s[kind]),upsert=usePKI(s=>s.upsert),remove=usePKI(s=>s.remove),toast=usePKI(s=>s.toast);const [edit,setEdit]=useState(null);const display=x=>x.name||x.commonName||x.email;return <Page title={title} sub={'Manage '+title.toLowerCase()} action={<button onClick={()=>setEdit({name:'',description:'',status:'Active'})}>Create</button>}><div className="cards3">{xs.slice(0,80).map(x=><div className="card managed" key={x.id}><div><h2>{display(x)}</h2><p>{x.description||x.email||x.type||x.role}</p></div><div className="tags">{x.status&&<Badge>{x.status}</Badge>}{x.algorithm&&<span>{x.algorithm}</span>}{x.severity&&<span>{x.severity}</span>}</div><div className="actions"><button className="secondary" onClick={()=>setEdit(x)}>Edit</button><button className="danger" onClick={()=>{remove(kind,x.id);toast('Record removed','warn')}}>Delete</button></div></div>)}</div>{edit&&<div className="modalback"><div className="modal"><div className="modalhead"><h2>{edit.id?'Edit':'Create'} {title}</h2><button className="icon" onClick={()=>setEdit(null)}>×</button></div><Field l="Name" v={edit.name||edit.email||''} set={v=>setEdit({...edit,name:v})}/><Field l="Description" v={edit.description||''} set={v=>setEdit({...edit,description:v})}/><Select l="Status" v={edit.status||'Active'} set={v=>setEdit({...edit,status:v})} a={['Active','Inactive','Enabled','Disabled','Online']}/><div className="actions"><button className="secondary" onClick={()=>setEdit(null)}>Cancel</button><button onClick={()=>{upsert(kind,edit);toast('Changes saved');setEdit(null)}}>Save Changes</button></div></div></div>}</Page>}

function Audit(){const xs=usePKI(s=>s.auditLogs),[q,setQ]=useState('');const rows=xs.filter(x=>(x.event+x.actor+x.target+x.details).toLowerCase().includes(q.toLowerCase())).slice(0,120);const csv=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([['timestamp,event,actor,target,details',...rows.map(x=>[x.timestamp,x.event,x.actor,x.target,x.details].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n')],{type:'text/csv'}));a.download='pki-audit.csv';a.click()};return <Page title="Audit Logs" sub="Searchable evidence of PKI lifecycle and administrative actions" action={<button onClick={csv}>Export CSV</button>}><div className="filters"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search audit evidence"/></div></div><Table cols={['Timestamp','Event','Actor','Target','Details','IP']} rows={rows.map(x=><tr key={x.id}><td>{new Date(x.timestamp).toLocaleString()}</td><td><b>{x.event}</b></td><td>{x.actor}</td><td>{x.target}</td><td>{x.details}</td><td>{x.ip}</td></tr>)}/></Page>}

function Alerts(){const xs=usePKI(s=>s.alerts),ack=usePKI(s=>s.acknowledgeAlert),[filter,setFilter]=useState('All');const rows=xs.filter(x=>filter==='All'||x.status===filter);return <Page title="Events & Alerts" sub="Security and operational events requiring attention"><div className="filters"><select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Open','Acknowledged','Dismissed'].map(x=><option key={x}>{x}</option>)}</select></div><Table cols={['Severity','Alert','Source','Timestamp','Status','Actions']} rows={rows.map(x=><tr key={x.id}><td><Badge>{x.severity}</Badge></td><td><b>{x.title}</b></td><td>{x.source}</td><td>{new Date(x.createdAt).toLocaleString()}</td><td><Badge>{x.status}</Badge></td><td><div className="rowactions">{x.status==='Open'&&<button onClick={()=>ack(x.id,'Acknowledged')}>Acknowledge</button>}{x.status!=='Dismissed'&&<button className="secondary" onClick={()=>ack(x.id,'Dismissed')}>Dismiss</button>}{x.status==='Dismissed'&&<span>Closed</span>}</div></td></tr>)}/></Page>}

function Health(){const xs=usePKI(s=>s.systems),[refresh,setRefresh]=useState(new Date());return <Page title="System Health" sub={'Service availability and operational telemetry • Refreshed '+refresh.toLocaleTimeString()} action={<button onClick={()=>setRefresh(new Date())}><RefreshCw size={16}/> Refresh</button>}><div className="cards3">{xs.map(x=><div className="card service" key={x.id}><div className="servicehead"><Activity/><Badge>{x.status}</Badge></div><h2>{x.name}</h2><div className="minirow"><span>Uptime</span><b>{x.uptime}%</b></div><div className="minirow"><span>Response</span><b>{x.response} ms</b></div><div className="minirow"><span>Last incident</span><b>{x.lastIncident}</b></div><div className="spark">{Array.from({length:18},(_,i)=><i key={i} style={{height:(22+((i*7+x.response)%28))+'px'}}/> )}</div></div>)}</div></Page>}

function Roles(){const roles=usePKI(s=>s.rolePermissions),users=usePKI(s=>s.users),upsert=usePKI(s=>s.upsert),[edit,setEdit]=useState(null);const perms=['cert.read','cert.write','request.create','approve','revoke','policy.manage','users.manage','audit.read','sign.create','sign.approve','sign.manage'];return <Page title="Roles & Permissions" sub="RBAC and separation-of-duties administration"><div className="card matrix"><table><thead><tr><th>Role</th><th>Users</th>{perms.map(p=><th key={p}>{p}</th>)}</tr></thead><tbody>{roles.map(r=><tr key={r.id}><td><button className="link" onClick={()=>setEdit(r)}>{r.name}</button></td><td>{users.filter(u=>u.role===r.name).length}</td>{perms.map(p=><td key={p}>{r.permissions.includes(p)?'✓':'—'}</td>)}</tr>)}</tbody></table></div>{edit&&<div className="modalback"><div className="modal wide"><div className="modalhead"><h2>Edit {edit.name}</h2><button className="icon" onClick={()=>setEdit(null)}>×</button></div><div className="permissiongrid">{perms.map(p=><label key={p}><input type="checkbox" checked={edit.permissions.includes(p)} onChange={e=>setEdit({...edit,permissions:e.target.checked?[...edit.permissions,p]:edit.permissions.filter(x=>x!==p)})}/>{p}</label>)}</div><div className="actions"><button className="secondary" onClick={()=>setEdit(null)}>Cancel</button><button onClick={()=>{upsert('rolePermissions',edit);setEdit(null)}}>Save Role</button></div></div></div>}</Page>}

function SettingsPage(){const current=usePKI(s=>s.settings),save=usePKI(s=>s.saveSettings),toast=usePKI(s=>s.toast),[f,setF]=useState(current);return <Page title="Settings" sub="Platform security, notification and lifecycle defaults"><div className="card formcard"><Field l="Organization Name" v={f.orgName} set={v=>setF({...f,orgName:v})}/><div className="formgrid"><Field l="Session Timeout (minutes)" v={f.sessionTimeout} set={v=>setF({...f,sessionTimeout:Number(v)})}/><Field l="Default Certificate Validity (days)" v={f.defaultValidity} set={v=>setF({...f,defaultValidity:Number(v)})}/></div>{[['MFA required','mfaRequired'],['Expiry alerts','expiryAlerts'],['Approval alerts','approvalAlerts'],['Email notifications','emailNotifications']].map(([l,k])=><label className="toggle" key={k}><span>{l}</span><input type="checkbox" checked={!!f[k]} onChange={e=>setF({...f,[k]:e.target.checked})}/></label>)}<div className="actions"><button onClick={()=>{save(f);toast('Settings saved')}}>Save Settings</button></div></div></Page>}

createRoot(document.getElementById('root')).render(<BrowserRouter><Shell/></BrowserRouter>);
