import {create} from 'zustand';import {persist} from 'zustand/middleware';import {seedDatabase} from './data';
const stamp=()=>new Date().toISOString();
const audit=(s,event,target,details,actor='Varsha')=>[{id:`AUD-${Date.now()}`,timestamp:stamp(),event,actor,target,details,ip:'127.0.0.1'},...s.auditLogs];
export const usePKI=create(persist((set,get)=>({
 ...seedDatabase(),toasts:[],
 toast:(message,type='success')=>{const id=Date.now();set(s=>({toasts:[...s.toasts,{id,message,type}]}));setTimeout(()=>set(s=>({toasts:s.toasts.filter(t=>t.id!==id)})),2600)},
 createRequest:(r)=>set(s=>{const rec={...r,id:`REQ-${Date.now()}`,createdAt:stamp(),status:'Pending',requester:'Varsha',history:[{at:stamp(),action:'REQUEST_CREATED'}]};return{requests:[rec,...s.requests],auditLogs:audit(s,'REQUEST_CREATED',rec.id,`Certificate request created for ${rec.commonName}`)}}),
 decideRequest:(id,decision)=>set(s=>{const req=s.requests.find(x=>x.id===id);if(!req)return s;let certificates=s.certificates;const status=decision==='approve'?'Approved':'Rejected';if(decision==='approve'){const exp=new Date();exp.setDate(exp.getDate()+Number(req.validity||365));certificates=[{id:`CERT-${Date.now()}`,commonName:req.commonName,type:req.type,environment:req.environment,issuer:req.environment==='Development'?'DEV-ICA-01':'PROD-ICA-01',issueDate:stamp(),expiryDate:exp.toISOString(),status:'Active',keyAlgorithm:req.keyAlgorithm,serial:Date.now().toString(16).toUpperCase(),sans:String(req.sans||'').split(',').filter(Boolean),owner:req.requester},...certificates]};return{requests:s.requests.map(x=>x.id===id?{...x,status,history:[...(x.history||[]),{at:stamp(),action:`REQUEST_${status.toUpperCase()}`}]}:x),certificates,auditLogs:audit(s,`REQUEST_${status.toUpperCase()}`,id,`${status} ${req.commonName}`)}}),
 updateCertificate:(id,action)=>set(s=>{const c=s.certificates.find(x=>x.id===id);if(!c)return s;let next={...c};if(action==='revoke'){next.status='Revoked';next.revokedAt=stamp();}if(action==='renew'){const d=new Date();d.setDate(d.getDate()+365);next.expiryDate=d.toISOString();next.status='Active'}return{certificates:s.certificates.map(x=>x.id===id?next:x),auditLogs:audit(s,`CERTIFICATE_${action.toUpperCase()}ED`,c.commonName,`${action} completed`)}}),
 createSigning:(r)=>set(s=>{const rec={...r,id:`SIGN-${Date.now()}`,createdAt:stamp(),requester:'Varsha',status:'Pending',history:[{at:stamp(),action:'SIGN_REQUESTED'}]};return{signingRequests:[rec,...s.signingRequests],auditLogs:audit(s,'SIGN_REQUESTED',rec.id,`Signing requested for ${rec.artifact}`)}}),
 decideSigning:(id,status)=>set(s=>({signingRequests:s.signingRequests.map(x=>x.id===id?{...x,status}:x),auditLogs:audit(s,`SIGN_${status.toUpperCase()}`,id,`Signing request ${status.toLowerCase()}`)})),
 upsert:(key,record)=>set(s=>{const exists=s[key].some(x=>x.id===record.id);const id=record.id||`${key.slice(0,3).toUpperCase()}-${Date.now()}`;const rec={...record,id,modifiedAt:stamp()};return{[key]:exists?s[key].map(x=>x.id===id?rec:x):[rec,...s[key]],auditLogs:audit(s,`${key.toUpperCase()}_${exists?'UPDATED':'CREATED'}`,id,`${rec.name||rec.title||id} ${exists?'updated':'created'}`)}}),
 remove:(key,id)=>set(s=>({[key]:s[key].filter(x=>x.id!==id),auditLogs:audit(s,`${key.toUpperCase()}_REMOVED`,id,'Record removed')})),
 acknowledgeAlert:(id,status)=>set(s=>({alerts:s.alerts.map(x=>x.id===id?{...x,status}:x),auditLogs:audit(s,'ALERT_UPDATED',id,`Alert ${status.toLowerCase()}`)})),
 saveSettings:(settings)=>set(s=>({settings,auditLogs:audit(s,'SETTINGS_UPDATED','organization','Security settings updated')})),
 reset:()=>set(seedDatabase())
}),{name:'pki-control-plane-db-v4'}));
